arm64: Revert "sigcontext: use standard __uint128_t type for vregs in struct fpsimd_context."
It causes this issue with the Android build system:

out/soong/.intermediates/vendor/lineage/build/soong/generated_kernel_includes/ge
n/usr/include/asm/sigcontext.h:53:2: error: unknown type name '__uint128_t'
        __uint128_t vregs[32];
        ^

Change-Id: Ia4cf9c0e2b6a32550ec6c4398139838add0b24a1